name: Update ckeditor4 submodule on master/major branch

on:
  schedule:
  - cron: "*/15 * * * *"

jobs:

  update-master:
    runs-on: ubuntu-latest
    name: update ckeditor submodule master

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - run: |
          ./dev/gh-actions/ckeditorupdate.sh

  update-major:
    runs-on: ubuntu-latest
    name: update ckeditor submodule major

    steps:
      - uses: actions/checkout@v2
        with:
          ref: major
      - run: |
          ./dev/gh-actions/ckeditorupdate.sh
