name: Update CKEditor 4 submodule

on:
  schedule:
  - cron: "*/15 * * * *"

jobs:

  update-master:
    runs-on: ubuntu-latest
    name: master

    steps:
      - name: Fetch changes
        uses: actions/checkout@v2
        with:
          ref: master
          submodules: true
      - run: |
          ./dev/gh-actions/ckeditorupdate.sh
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master

  update-major:
    runs-on: ubuntu-latest
    name: major

    steps:
      - name: Fetch changes
        uses: actions/checkout@v2
        with:
          ref: major
          submodules: true
      - run: |
          ./dev/gh-actions/ckeditorupdate.sh
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: major
